webapp/main/controllers.py
import os 
import logging
import numpy as np
from flask import (Blueprint, flash, jsonify, render_template, 
                   url_for, request, redirect, session, current_app)
from flask_login import login_required


from webapp import db, celery
from .forms import featuresForm
from .models import Features
from ..predict import predict_input, predict_time
from ..notify import nofication

main_blueprint = Blueprint("main", __name__)

logging.basicConfig(format='%(asctime)s:%(levelname)s:%(name)s:%(message)s')
logging.getLogger().setLevel(logging.DEBUG)
logger = logging.getLogger(__name__)

@main_blueprint.route('/')
def index():
    return render_template("main/index.html")

@main_blueprint.route("/about")
def about():
    return render_template("main/about.html")

@main_blueprint.route("/predict", methods=['POST', 'GET'])
def predict():
    form = featuresForm()
    if request.method == 'POST' and form.validate_on_submit():
        gender = form.gender.data
        age = form.age.data
        hrs_slept = form.hrs_slept.data
        sleep_qlt = form.leep_qty.data
        food = form.food_taken.data
        food_amt = form.food_amount.data
        drink = form.drinks.data
        temp = form.temperatures.data
        exercise = form.exercise.data
        medication = form.medication.data
        restroom = form.visit_restroom.data
        times_rest = form.times_rest.data
        tel = form.tel.data
        name = form.name.data
        
        features = [gender, age, hrs_slept, sleep_qlt, food, food_amt,
                             drink, temp, exercise, medication, restroom, times_rest]
        
        label, probability = predict_input(features)
        duration = predict_time(features)
        try:
            features = Features(gender=gender, age=age, hrs_slept=hrs_slept, sleep_quality=sleep_qlt,
                                food_taken=food, food_amount=food_amt, drink=drink,
                                temperatures=temp, exercise=exercise, medication=medication,
                                visit_restroom=restroom, times_visited=times_rest, 
                                caregiver=form.tel.data, child_name=form.name.data, 
                                predicted=label, probability=probability, time=duration)
            
            session['time'] = duration            
            if name:
                session['name'] = name
            if tel:
                session['receiver'] = tel
                nofication(current_app, 
                           receiver=tel, 
                           sender=current_app.config['TWILIO_SENDER'], 
                           name=name, time=duration)
                reminder_time = max(duration - 5, 0)
                reminder_notification.apply_async((tel, name, 5), countdown=reminder_time*60)
            db.session.add(features)
            db.session.commit()         
            return redirect(url_for('main.results'))
        except Exception as e:
            db.session.rollback()
            logger.error(f"Error when generating prediction: {e}")
            flash(f"The prediction was not successful, kindly try again", category='warning')
    return render_template("main/predict.html", form=form)

@celery.task()
def reminder_notification(telephone, name, time):
    nofication(current_app, 
               receiver=telephone,
               name=name,
               time=time)

@main_blueprint.route('/thanks')
def results():
    name = session.get('name')
    time = session.get('time')
    tel = session.get('receiver')
    return render_template('main/result.html', name=name, duration=time, tel=tel)
        
@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    return render_template('main/dashboard.html')


        

webapp/templates/include/footer.html
<div class="topaz">
    <div class="logo">
        <h2>WeLove</h2>
        <i class="fa fa-people-carry-box"></i>
        <small>Where <span>Love</span>, <span>Care</span>, <span>Passion</span>, and <span>Compassion</span> thrive.</small>
    </div>
    <div class="subscribe">
        <h3>Subscribe To Our Mailing List</h3>
        <p>Receive personalized recommendations on how to improve the childs toileting habits.</p>
        <div class="input-group">
            <input type="email" name="email" id="subscribe">
            <button type="submit" class="input-group-append">Subscribe</button>
        </div>              
    </div>
</div>
<div class="contents">
    <div class="essentials">
        <h3>WeLove, We Care.</h3>
        <ul>
            <li>
                <a href="">Data Collection & Privacy</a>
            </li>
            <li>
                <a href="">Ethical Considerations</a>
            </li>
            <li>
                <a href="">Model Biasness</a>
            </li>
            <!-- <li>
                <a href="">Terms of Use</a>
            </li> -->
            <li>
                <a href="">FAQ</a>
            </li>
        </ul>            
    </div>
    <div class="contact">
        <h3>Visit Or Reach Out To Us Today.</h3>
        <ul>
            <li>
                <a href="">
                    <i class="fa fa-map-pin"></i>
                    Westpark Towers, 2nd Flr, Westlands, Nairobi.
                </a>
            </li>
            <li>
                <a href="mailto:info.welove@gmail.com">
                    <i class="fa fa-envelope"></i>
                    info.welove@gmail.com
                </a>
            </li>
            <li>
                <a href="tel:">
                    <i class="fa fa-phone"></i>
                    +254-712-345-678
                </a>
            </li>
            <li>
                <a href="https://api.whatsapp.me/">
                    <i class="fa-brands fa-whatsapp"></i>
                    +254-112-345-678
                </a>
            </li>
        </ul>
    </div>
    <div class="follow">
        <h3>Let's Spread Love Together.</h3>
        <ul>
            <li>
                <a href="">
                    Twitter
                    <i class="fa-brands fa-twitter"></i>
                </a>
            </li>
            <li>
                <a href="">
                    Facebook
                    <i class="fa-brands fa-facebook"></i>
                </a>
            </li>
            <li>
                <a href="">
                    Instagram
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </li>
            <li>
                <a href="">
                    TikTok
                    <i class="fa-brands fa-tiktok"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="copy">
    <p>&copy;2024.WeLove.All rights reserved.</p>

    <p>Made with <i class="fa fa-heart"></i> by WeLove Team.</p>        
</div>

webapp/templates/include/navigation.html
<nav id="nav">
    <ul class="nav-items">
        <li class="nav-item" data-url="{{ url_for('main.index') }}">
            WeLove
            <i class="fa fa-people-carry-box"></i>
        </li>
        <li class="nav-item" data-url="{{ url_for('main.about') }}">
            About
        </li>
        {% if current_user.is_anonymous %}
        <li class="nav-item" id="sign" data-url="{{ url_for('auth.login')}}">
            <span>Sign-In</span> <i class="fa fa-sign-in"></i>
        </li>
        {% else %}
        <li class="user">
            <span id="dropdown">
                {{ current_user.username | title }}
                <img src="{{ url_for('static', filename='images/user.jpg')}}" alt="">
            </span>
            <ul id="dropdown-menu">
                <li class="nav-item">
                    Profile
                </li>
                <li class="nav-item" data-url="{{ url_for('main.dashboard') }}">
                    Dashboard
                </li>
                <li class="nav-item" id="log" data-url="{{ url_for('auth.logout') }}">
                    Log out <i class="fa fa-sign-out"></i>
                </li>
            </ul>
        </li>
        {% endif %}
    </ul>
</nav>