flaskapp/webapp/main/forms.py
from flask_wtf import FlaskForm
import phonenumbers.util
from wtforms import StringField, IntegerField, TelField, SelectField, RadioField, DecimalRangeField
from wtforms.validators import DataRequired, Optional, Length, NumberRange, ValidationError, InputRequired

import phonenumbers

class featuresForm(FlaskForm):
    gender = RadioField("Select Gender", validators=[DataRequired()], choices=[("Male", "Male"), ("Female", "Female")])
    age = IntegerField("Age of the child", validators=[DataRequired(), NumberRange(min=3, max=15)])
    hrs_slept = IntegerField("How many hours slept?", validators=[DataRequired(), NumberRange(min=0, max=15)])
    leep_qty = SelectField("Sleep quality", validators=[DataRequired()],
                           choices=[(" ", "-----Select Option-----"), ("Excellent", "Excellent"),
                                    ("Good", "Good"), ("Concerning", "Concerning"), 
                                    ("Worse", "Worse"), ("Worst", "Worst")])
    food_taken = SelectField("Food taken", validators=[DataRequired()], 
                             choices=[(" ", "-----Select Option-----"), ("Ugali", "Ugali"), 
                                      ("Chapati", "Chapati"), ("Meat", "Meat"), ("Rice", "Rice"),
                                      ("Fruits", "Fruits"), ("Veggies", "Veggies"), ("Snacks", "Snacks")])
    food_amount = RadioField("Amout of food taken", validators=[DataRequired()],
                              choices=[("Heavy", "Heavy"), ("Normal", "Normal"), ("Small", "Small")])
    drinks = SelectField("Drinks taken", validators=[DataRequired()],
                         choices=[(" ", "-----Select Option-----"), ("Coffee", "Coffee"), 
                                  ("Tea", "Tea"), ("Porridge", "Porridge"), ("Soft Drink", "Soft Drink"), 
                                  ("Milk", "Milk"), ("Water", "Water")])
    temperatures = IntegerField("Average temperature", validators=[DataRequired(), NumberRange(min=10.0, max=40.0)])
    exercise = RadioField("Involved in any form of execise?", validators=[DataRequired()],
                          choices=[('Yes', "Yes"), ("No", "No")])
    medication = RadioField("Any medication taken?", validators=[DataRequired()],
                             choices=[("Yes", "Yes"), ("No", "No")])
    visit_restroom = RadioField("Visited rest room today?", validators=[DataRequired()],
                                choices=[("Yes", "Yes"), ("No", "No")])
    times_rest = IntegerField("If yes, how many times?", validators=[InputRequired(), NumberRange(min=0, max=10)])
    tel = TelField("Caregiver/parent mobile", validators=[Optional()])
    name = StringField("Name of the child", validators=[Optional()])
    
    
    def validate_tel(form, field):
        try:
            telephone = phonenumbers.parse(field.data)
            if not phonenumbers.is_valid_number(telephone):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            raise ValidationError("Invalid phone number.")
                

flaskapp/webapp/main/controllers.py
import os 
import numpy as np
from flask import (Blueprint, flash, jsonify, render_template, 
                   url_for, request, redirect, session, current_app)
from flask_login import login_required


from webapp import db, celery
from .forms import featuresForm
from .models import Features
from ..predict import predict_input, predict_time
from ..notify import nofication

main_blueprint = Blueprint("main", __name__)

@main_blueprint.route('/')
def index():
    return render_template("main/index.html")

@main_blueprint.route("/about")
def about():
    return render_template("main/about.html")

@main_blueprint.route("/predict", methods=['POST', 'GET'])
def predict():
    form = featuresForm()
    if request.method == 'POST' and form.validate_on_submit():
        gender = form.gender.data
        age = form.age.data
        hrs_slept = form.hrs_slept.data
        sleep_qlt = form.leep_qty.data
        food = form.food_taken.data
        food_amt = form.food_amount.data
        drink = form.drinks.data
        temp = form.temperatures.data
        exercise = form.exercise.data
        medication = form.medication.data
        restroom = form.visit_restroom.data
        times_rest = form.times_rest.data
        tel = form.tel.data
        name = form.name.data
        
        features = np.array([[gender, age, hrs_slept, sleep_qlt, food, food_amt,
                             drink, temp, exercise, medication, restroom, times_rest]])
        
        label, probability = predict_input(features)
        duration = predict_time(features)
        try:
            features = Features(gender=gender, age=age, hrs_slept=hrs_slept, sleep_quality=sleep_qlt,
                                food_taken=food, food_amount=food_amt, drink=drink,
                                temperatures=temp, exercise=exercise, medication=medication,
                                visit_restroom=restroom, times_visited=times_rest, 
                                caregiver=form.tel.data, child_name=form.name.data, 
                                predicted=label, probability=probability, time=duration)
            
            session['time'] = duration            
            if name:
                session['name'] = name
            if tel:
                session['receiver'] = tel
                nofication(current_app, 
                           receiver=tel, 
                           sender=current_app.config['TWILIO_SENDER'], 
                           name=name, time=duration)
                reminder_time = max(duration - 5, 0)
                reminder_notification.apply_async((tel, name, 5), countdown=reminder_time*60)
            db.session.add(features)
            db.session.commit()         
            return redirect(url_for('main.results'))
        except Exception as e:
            db.session.rollback()
            flash(f"The prediction was not successful, kindly try again. {e}", category='warning')
    return render_template("main/predict.html", form=form)

@celery.task()
def reminder_notification(telephone, name, time):
    nofication(current_app, 
               receiver=telephone,
               name=name,
               time=time)

@main_blueprint.route('/thanks')
def results():
    name = session.get('name')
    time = session.get('time')
    return render_template('main/result.html', name=name, duration=time)
        
@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    return render_template('main/dashboard.html')


        

flaskapp/webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.4.0/font/bootstrap-icons.min.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/@webpixels/css@1.1.5/dist/index.css"> -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='font/css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
    
</head>
<body>
    <div class="messages" id="messages" style="position: fixed; max-width: 50%; bottom: 0; right: 0; z-index: 3;">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" fade show role="alert">
                    <button type="button" class="exit" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="info">
                        <span><i class="fa fa-info-circle"></i> {{ message }}.</span>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}        
    </div>
    <header>
        {% block header %}
            {% include 'include/navigation.html' %}
        {% endblock %}
    </header>
    <main>
        {% block content %}{% endblock %}        
    </main>
    <footer>
        {% block footer %}
            {% include 'include/footer.html' %}
        {% endblock %}        
    </footer>

    {% block js %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

flaskapp/webapp/templates/main/about.html
{% extends 'base.html' %}

{% block title %}WeLove - About us{% endblock %}

{% block content %}
<section class="about">
    <figure>
        <img src="{{ url_for('static', filename='images/net.jpg') }}">
        <main>
            <h3>Who is WeLove?</h3>
        </main>
    </figure>
    <div class="tea">
        <p>
            WeLove was born out of a shared passion for making a meaningful difference in the lives of 
            persons with disabilities (PWDs). Our journey began at KISE during a hackathon, where a domain experts, various stakeholders and a group of students 
            came together with a common goal: to harness technology and innovation to address the challenges faced by PWDs.
        </p><br>
        <p>
            Inspired by our compassion and empathy for individuals with disabilities, we embarked on a journey of exploration and discovery. 
            Through collaborative brainstorming sessions and tireless effort, we honed in on the pressing issue of toilet 
            training for disabled children particularly children with autism spectrum disorder (ASD). Recognizing the significant 
            impact that effective toilet training can have on a child's independence and quality of life, we were determined to 
            find a solution.
        </p><br>
        <p>
            Driven by a commitment to making a positive impact, we embarked on a collaborative effort to harness the power of 
            artificial intelligence and machine learning in creating our unique toilet training assistance app. 
            Through insightful conversations and in-depth research, we gained a deep understanding of the complex needs and 
            struggles faced by children with ASD and their caregivers during the toilet training process.
        </p><br>
        <p>
            Drawing from our collective expertise and experiences, we designed WeLove to be more than just a tool—it's a beacon 
            of hope and empowerment for families navigating the challenges of toilet training. By providing personalized 
            recommendations, progress tracking, and educational resources, we strive to offer comprehensive support tailored 
            to each child's unique journey.
        </p><br>
        <p>
            Our team is driven by a shared mission: to transform the lives of disabled children and their families by equipping 
            them with the tools and resources they need to succeed. With dedication, innovation, and compassion at the core of 
            everything we do, we are committed to making a meaningful difference in the lives of those we serve.
        </p><br>
        <p>
            As young professionals, we are dedicated to making a positive impact in our communities and beyond. WeLove represents 
            our commitment to innovation, inclusivity, and compassion, and we are proud to be part of this transformative journey.
        </p>        
    </div>
</section>
<section class="values">
    <img src="{{ url_for('static', filename='images/coaster.png') }}" alt="">
    <h3>Our core values</h3>
    <div class="cores">
        <ul>
            <h4>At WeLove, we embody:-</h4>
            <li><i class="fa fa-heart"></i> Empathy </li>
            <li><i class="fa fa-people-roof"></i> Inclusivity </li>
            <li><i class="fa fa-lightbulb"></i> Innovation </li>
            <li><i class="fa fa-people-group"></i> Collaboration </li>
            <li><i class="fa fa-person-cane"></i> Empowerment </li>
            <li><i class="fa fa-handshake"></i> Integrity </li>
        </ul> 
        <div class="core-values">
            <details>
                <summary>Empathy</summary>
                <p>
                    We believe in understanding and empathizing with the experiences and challenges faced by individuals 
                    with disabilities and their families. By putting ourselves in their shoes, we strive to develop solutions
                    that are truly impactful and meaningful.
                </p>
            </details>       
            <details>
                <summary>Inclusivity</summary>
                <p>
                    We are committed to creating an inclusive environment where everyone, regardless of ability, is valued 
                    and respected. Our solutions are designed to be accessible and beneficial to individuals with a wide 
                    range of disabilities.
                </p>
            </details>
            <details>
                <summary>Innovation</summary>
                <p>
                    We embrace innovation and creativity as drivers of positive change. Through continuous research, 
                    development, and iteration, we seek to push the boundaries of what is possible and find new ways to 
                    improve the lives of individuals with disabilities.
                </p>
            </details>
            <details>
                <summary>Collaboration</summary>
                <p>
                    We believe in the power of collaboration and teamwork. By working together with individuals, families, 
                    caregivers, and experts in the field, we can leverage diverse perspectives and expertise to create more 
                    effective and impactful solutions.
                </p>
            </details>
            <details>
                <summary>Empowerment</summary>
                <p>
                    We are dedicated to empowering individuals with disabilities to live fulfilling and independent lives. 
                    Our solutions are designed to provide them with the tools, resources, and support they need to overcome 
                    challenges, achieve their goals, and realize their full potential.
                </p>
            </details>            
            <details>
                <summary>Integrity</summary>
                <p>
                    We uphold the highest standards of integrity, honesty, and transparency in everything we do. 
                    We are committed to earning the trust and confidence of our users, partners, and stakeholders through 
                    ethical and responsible conduct.
                </p>
            </details>
        </div>
    </div>
</section>
<section class="team">
    <h3>Our team.</h3>
    <div class="team-cards">
        <div class="mate" id="riri">
            <h4 class="whoIs">Meet Riri </h4>
            <div class="prof">
                <img src="{{ url_for('static', filename='images/user.png')}}" alt="Riri profile picture">
                <div class="titles">
                    <h4>James Riri.</h4>
                    <h5>ML Engineer</h5>
                </div>
            </div>
            <div class="flex">
                <strong>Meet Riri, our ML Engineer:</strong> 
                <p>
                    James is the engine behind our machine learning models, bringing them to life with precision and 
                    expertise. With a deep understanding of algorithms and programming languages, James builds and 
                    optimizes AI models that power our innovative solutions. His dedication to pushing the boundaries 
                    of machine learning drives our quest for innovation.
                </p>
            </div>
            <div class="socials">
                <ul>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-medium"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-github"></i>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
        <div class="mate" id="martha">
            <h4 class="whoIs">Meet Martha</h4>
            <div class="prof">
                <img src="{{ url_for('static', filename='images/user.jpg')}}" alt="Martha profile picture">
                <div class="titles">
                    <h4>Martha Murugi.</h4>
                    <h5>Data Scientist</h5>
                </div>
            </div>
            <div class="flex">
                <strong>Introducing Murugi, our Data Scientist:</strong> 
                <p>
                    Armed with a keen analytical mind and a deep understanding of 
                    data, Martha leads the charge in uncovering insights and patterns from complex datasets. 
                    Her expertise in statistical analysis and machine learning algorithms enables WeLove to harness 
                    the power of data to drive impactful decisions and solutions.
                </p>
            </div>
            <div class="socials">
                <ul>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-medium"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-github"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="mate" class="jose">
            <h4 class="whoIs">Meet Jose</h4>
            <div class="prof">
                <img src="{{ url_for('static', filename='images/user.png')}}" alt="Josephat profile picture">
                <div class="titles">
                    <h4>Josephat Onkoba.</h4>
                    <h5>MLOps Expert</h5>
                </div>
            </div>
            <div class="flex">
                <strong>Say hello to Onkoba, our MLOps Expert:</strong> 
                <p>
                    With a passion for deploying machine learning models at scale, Josephat brings 
                    extensive expertise in MLOps to the WeLove team. With his knack for optimizing machine learning 
                    workflows and ensuring seamless integration between development and deployment pipelines, 
                    Josephat plays a crucial role in bringing our innovative solutions to life.
                </p>
            </div>
            <div class="socials">
                <ul>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-medium"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-brands fa-github"></i>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <!-- <p>
        Together, Josephat, Martha, and James form a dynamic and talented trio dedicated to harnessing the power of technology 
        to make a positive impact in the lives of individuals with disabilities. With their combined expertise and passion, 
        WeLove is poised to revolutionize the field of assistive technology and empower individuals to live their best lives.
    </p> -->
</section>
{% endblock %}

flaskapp/webapp/templates/main/index.html
{% extends 'base.html' %}

{% block title %}WeLove - Home {% endblock %}

{% block content %}
<section class="index">
    <h1>WeLove</h1>
    <h2>Your Personalized Toilet Training Assistant</h2>
    <div class="highlights">
        <p>
            An app dedicated to transforming the lives of disabled children and their families through innovative 
            solutions for toilet training.
        </p>
        <p>
            Utilize advanced AI algorithms to analyze data related to your child's toileting 
            habits and consequently get personalized recommendations tailored for your child's specific needs, 
            optimizing the toilet training process.
        </p>
        <p> 
            Get key metrics and receive insights into the child's toileting habits, helping to ensure steady improvement
            and success in toilet training.
        </p>
        <p>
            Receive educational resources that empower parents and caregivers with the knowledge and information 
            they need to support their child's development.
        </p>
    </div>
</section> 
<section class="extra">
    <div class="info">
        <img src="{{ url_for('static', filename='images/check.png')}}" alt="">
        <h3>Key Features:</h3>
        <h4>1.Personalized Recommendations: </h4>
        <p>
            WeLove analyzes data provided by users, such as toileting habits, diet, and meal schedules, to generate personalized recommendations for effective toilet training. 
            These recommendations are tailored to each child's unique needs and preferences, helping parents and caregivers navigate 
            the challenges of toilet training with confidence.            
        </p>
        <h4>2. Educational Resources: </h4>
        <p>
            WeLove offers a wealth of educational resources, including articles, tips, and guides on effective toilet training 
            techniques. Whether it's understanding toileting readiness cues or implementing positive reinforcement strategies, 
            WeLove aims to equip users with the knowledge and information they need to support their child's development.            
        </p>
        <p>
            With WeLove by your side, toilet training becomes a more manageable and rewarding experience for both parents 
            and children. Interact with WeLove today and embark on this journey towards independence and success!.            
        </p>
        <button id="try" data-url="{{ url_for('main.predict') }}">Try WeLove</button>
    </div>
    <div class="facts">
        <h3>Did you know? <i class="fa fa-lightbulb" id="center"></i> </h3>

        <details>
            <summary>Toilet Training Challenges</summary>
            <p>
                Children with autism spectrum disorder (ASD) often experience challenges with toilet training, 
                with studies indicating that they may take longer to achieve continence compared to typically developing 
                children.
            </p>
        </details>
        <details>
            <summary>Sensory Processing Capabilities</summary>
            <p>
                Research suggests that children with ASD may have difficulties recognizing and responding to bodily cues 
                related to toileting, leading to delays in toilet training readiness.
            </p>
            </details>
        <details>
            <summary>Effectiveness of Behavioral Interventions</summary>
            <p>
                A study published in the Journal of Developmental and Behavioral Pediatrics found that behavioral 
                interventions, such as applied behavior analysis (ABA), can be effective in promoting successful toilet 
                training outcomes for children with ASD.
            </p>
        </details>
        <details>
            <summary>Use of Visual Support</summary>
            <p>
                According to research published in the Journal of Autism and Developmental Disorders, visual supports, 
                such as picture schedules and social stories, have been shown to be beneficial in teaching toileting 
                skills to children with ASD.
            </p>
        </details>
        <details>
            <summary>Reinforcement and Consistency</summary>
            <p>
                Studies have indicated that establishing a consistent toileting routine and providing positive 
                reinforcement for successful toileting behaviors are key components of successful toilet training 
                for children with ASD.
            </p>
        </details>    
</section>   
{% endblock %}
{% block js %}
<script>
    var toCenter = [ '#center', '.highlighdts']    
    var tryMe = document.getElementById("try");

    tryMe.addEventListener('click', function(){
        var url = tryMe.getAttribute("data-url");
        window.location.href = url;
    });

    toCenter.forEach(function(center){
        var item = document.querySelector(center);

        var elementHeight = item.clientHeight;
        var elementWidth = item.clientWidth;

        var windowHeight = window.innerHeight;
        var windowWidth = window.innerWidth;

        var leftPosition = (windowWidth - elementWidth) / 2;
        var topPosition = (windowHeight - elementHeight) / 2;

        item.style.left = leftPosition + 'px';
        item.style.top = topPosition + 'px';
    });

</script>
{% endblock %}